config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :cities, :only => [:index]
  resources :hotels, :only => [:index, :show]
  resources :reservations, :only => [:index, :show]
  resources :reviews, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :users, :only =>[:create, :show]
  
  # Sessions controller routes
  root 'sessions#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/signup', to: 'users#new', as: 'signup'

  # Omniuath routes
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  #  Amadeus API routes
  get "hotel_search", to: "hotels#index"
  get "search_results", to: "hotels#search_results"
  get "/reserve/:hotelId/:code", to: "hotels#reserve"

  # Nested routes
  resources :cities, only: [:show] do
    resources :hotels, only: [:index, :show]
  end

  resources :users, only: [:show] do
    resources :hotels, only: [:index]
  end

  resources :reservations, only: [:show] do
    resources :reviews, only: [:show, :new]
  end

  get 'trending', to: 'hotels#trending'
  get 'datalist', to: 'cities#datalist'

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
  has_one :room
  has_one :review
  
  # Method used in the select fields of the new review form 
  def hotel_and_checkin
    "#{self.hotel.name}, check-in: #{self.checkin_date}"
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = current_user.reservations.any?
  end

  #  The show action uses the hotels/show template; reservations don't have their own show page
  def show
    @single_reservation = current_user.reservations.find_by(id: params[:id]) 
    if @single_reservation
      @hotel = @single_reservation.hotel
      render :'hotels/show.html.erb' 
    else 
      flash[:msg] = "Reservation not found"
      redirect_to reservations_path 
    end
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper

  def upcoming_single_reservation?(reservation)
    reservation.checkin_date >= Date.today.to_s
  end

  def open_for_review?(reservation)
    reservation.checkout_date < Date.today.to_s
  end

end

app/views/reservations/_info.html.erb
<div class="reservation">
  <p>
    Check-in Date: <%= reservation.checkin_date %><br>
    Check-out Date: <%= reservation.checkout_date %><br>
    Guests: <%= reservation.guests %><br>
    Price: <%= reservation.currency %> <%= reservation.price %><br>
  <% if reservation.review %>
    <%= link_to 'Show review', reservation_review_path(reservation, reservation.review) %>
  <% elsif open_for_review?(reservation) %>  
    <%= link_to 'Write a review', new_reservation_review_path(reservation) %>
  <% end %>
  </p>
</div>

app/views/reservations/_info_no_links.html.erb
Check-in Date: <%= reservation.checkin_date %><br>
Check-out Date: <%= reservation.checkout_date %><br>
Guests: <%= reservation.guests %><br>
Price: <%= reservation.currency %> <%= reservation.price %>

app/views/reservations/index.html.erb
<%= render partial: 'messages/msg' %>

<h1>My Reservations</h1><br>

<% if !@reservations %>
  <p>It seems you haven't booked any reservations yet :)</p>
<% else %>

  <% upcoming_reservations = @user.upcoming_reservations %>
  <% if !upcoming_reservations.empty? %>
    <p>Upcoming:</p>
    <ul>
      <% upcoming_reservations.each do |reservation| %>
        <li>
          <h3><%= link_to reservation.hotel.name, reservation_path(reservation) %></h3>
          <%= reservation.hotel.city.name %>
          <%= render 'reservations/info', :reservation => reservation %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% previous_reservations = @user.previous_reservations %>
  <% if !previous_reservations.empty? %>
    <p>Previous:</p>
    <ul>
      <% previous_reservations.each do |reservation| %>
        <li>
          <h3><%= link_to reservation.hotel.name, reservation_path(reservation) %></h3>
          <%= reservation.hotel.city.name %>
          <%= render 'reservations/info', :reservation => reservation %>
        </li>
      <% end %>
    </ul>
  <% end %>

<% end %>