config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :cities, :only => [:index]
  resources :hotels, :only => [:index, :show]
  resources :reservations, :only => [:index, :show]
  resources :reviews, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :users, :only =>[:create, :show]
  
  # Sessions controller routes
  root 'sessions#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/signup', to: 'users#new', as: 'signup'

  # Omniuath routes
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  #  Amadeus API routes
  get "hotel_search", to: "hotels#index"
  get "search_results", to: "hotels#search_results"
  get "/reserve/:hotelId/:code", to: "hotels#reserve"

  # Nested routes
  resources :cities, only: [:show] do
    resources :hotels, only: [:index, :show]
  end

  resources :users, only: [:show] do
    resources :hotels, only: [:index]
  end

  resources :reservations, only: [:show] do
    resources :reviews, only: [:show, :new]
  end

  get 'trending', to: 'hotels#trending'
  get 'datalist', to: 'cities#datalist'

end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :reservations
  has_many :users, through: :reservations
  has_many :reviews, through: :reservations
  belongs_to :city

  include Normalizable::Parse
  
  # Since a hotel comes with a reservation and a room, hotels are built with both objects nested
  def self.build_hotel(hotel_hash, user_id)
    city = City.find_or_create_by(code: hotel_hash["hotel"]["cityCode"], name: hotel_hash["hotel"]["address"]["cityName"].titleize)
    hotel = Hotel.find_by(hotelId: hotel_hash["hotel"]["hotelId"])
    # If the hotel is already in the database, do not build a new hotel (skip the below block)
    unless hotel 
      hotel = Hotel.new 
      hotel.city_id = city.id
      hotel.hotelId = hotel_hash["hotel"]["hotelId"]
      hotel.citycode = hotel_hash["hotel"]["cityCode"]
      hotel.name = hotel.general_parsing(hotel_hash["hotel"]["name"])     # 'general_parsing' method comes from the Normalizable module
      hotel.latitude = hotel_hash["hotel"]["latitude"]
      hotel.longitude = hotel_hash["hotel"]["longitude"]
      hotel.address = hotel.parse_address(hotel_hash["hotel"]["address"])   # 'parse_address' method comes from the Normalizable module
      # hotel.description = hotel.general_parsing(hotel_hash["hotel"]["description"]["text"]) unless !hotel_hash["hotel"].keys.include?("description")         # Some hotels do not inlcude a description
      hotel.description = hotel_hash["hotel"]["description"]["text"] unless !hotel_hash["hotel"].keys.include?("description")         # Some hotels do not inlcude a description
      hotel.amenities = hotel.general_parsing(hotel_hash["hotel"]["amenities"].take(5).join(", ")) unless !hotel_hash["hotel"].keys.include?("amenities")    # Some hotels do not include amenities
    end
    #  Build nested reservation for hotel 
    new_reservation = hotel.reservations.build(
      code: hotel_hash["offers"][0]["id"],                       # Reservation code in schema, reservations
      guests: hotel_hash["offers"][0]["guests"]["adults"],       # Number of guests
      currency: hotel_hash["offers"][0]["price"]["currency"],    # Currency
      price: hotel_hash["offers"][0]["price"]["total"],          # Total price
      checkin_date: hotel_hash["offers"][0]["checkInDate"],      # Checkin date
      checkout_date: hotel_hash["offers"][0]["checkOutDate"],    # Checkout date
    )
    new_reservation.user_id = user_id
    #  Build nested room for reservation 
    # If the hotel_hash includes the "TypeEstimated" key, build a room with 3 attributes
    if hotel_hash["offers"][0]["room"].keys.include?("typeEstimated")
      new_room = new_reservation.build_room(
        category: hotel_hash["offers"][0]["room"]["typeEstimated"]["category"],
        beds: hotel_hash["offers"][0]["room"]["typeEstimated"]["beds"],             # Number of beds
        bedtype: hotel_hash["offers"][0]["room"]["typeEstimated"]["bedType"]        # King, ect.
      )
    else
    # If the hotel_hash does not include the "TypeEstimated" key, build a rooom with one attribute only
      new_room = new_reservation.build_room(
        category: hotel_hash["offers"][0]["room"]["description"]["text"].split("\n")[1]
      )
    end
    # Return the hotel with its nested reservation and room
    # The hotel is not persisted to database unless a reservatino is made; see hotels_controller 'reserve' method
    hotel
  end

  def self.most_popular
    Hotel.all.sort do |a,b|
      b.reservation_ids.length <=> a.reservation_ids.length
    end.take(3)
  end
  
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :check_city_id, only: [:index, :show]
  before_action :check_user_id, only: [:index]

  def index
    # If the city_hotels nested route is used, display hotels from the nested city only (:check_city_id filter)
    # If the user_hotels nested route is used, display the user hotels (:check_user_id filter)
    # If no nested route is used, load the API for searching hotels (the below lines)
    if params[:city] && !params[:city].blank?
      city_code = filter_city_name
      api = AmadeusApi.new
      AmadeusApi.hotels.clear
      user_id = current_user.id
      flash[:msg] = ""
      begin
        @hotels = api.query_city(city_code, convert_dates[0], convert_dates[1], params[:guests], user_id)
      rescue Amadeus::ResponseError => e
        flash[:msg] = "#{e.class}: #{e.message}. Invalid city code or input value. Please try again..."
        render :'index.html.erb' and return
      end
      if @hotels.empty?
        flash[:msg] = "Ooops, no hotels could be found for the requested specifications"
      end
    end
  end

  def show
    # If request comes from the 'city/hotel' nested route, check that the city and the hotel are valid (:check_city_id filter)
    # If request comes from 'hotel_path',show the hotel from the database by user id and hotel id
    @hotel = current_user.find_hotel(params[:id])
    if @hotel.nil?
      flash[:msg] = "Hotel not found." 
      redirect_to user_hotels_path(current_user) and return
    end
  end

  def search_results
    @hotel = AmadeusApi.hotels.find { |hotel| hotel.hotelId == params[:hotelId] }
    if @hotel.nil?
      flash[:msg] = "Hotel not found." 
      redirect_to hotels_path and return
    end
    render :show
  end

  def reserve
    api = AmadeusApi.all.last
    @hotel = AmadeusApi.hotels.find { |hotel| hotel.hotelId == params[:hotelId] }
    begin
      # Use the HOTEL_OFFER API ENDPOINT to check in real-time whether the reservation is still available 
      reservation = api.amadeus.shopping.hotel_offer(params[:code]).get.data 
    rescue Amadeus::ResponseError => e
      flash[:msg] = "#{e.class}: #{e.message}. Please try again..."
      redirect_to root_path
    else 
      # If no exception is raised, check whether reservertion is avaiable
      if reservation && reservation["available"]  == true
        # Check that the reservation attributes did not change since first time reservation was displayed
        original = @hotel.reservations.last
        checkin = reservation["offers"][0]["checkInDate"] 
        checkout = reservation["offers"][0]["checkOutDate"] 
        guests = reservation["offers"][0]["guests"]["adults"] 
        # price = reservation["offers"][0]["price"]["total"] == @hotel.last_reservation.price
        if checkin == original.checkin_date && checkout == original.checkout_date && guests && original.guests #&& price
          AmadeusApi.hotels.clear
          @hotel.save
          # Update caches
          checkin = checkin.to_time.to_i
          Rails.cache.redis.with { |c| c.zadd(HotelTracker.hotels_list_cache_key(@user), checkin, @hotel.id, gt: true) } 
          Rails.cache.redis.with { |c| c.zadd(CityTracker.cities_list_cache_key(@user), checkin, @hotel.city_id, gt: true) }
          Rails.cache.redis.with { |c| c.incr(HotelTracker.upcoming_re_counter_cache_key(@user)) } 

          flash[:msg] = "Congratulations! Your reservation was successfully processed."
          redirect_to hotel_search_path
        else
          flash[:msg]= "Sorry, one or more of the reservation conditions have changed. Please retry your hotel search."
          render :'show.html.erb' and return
        end
      else
        flash[msg] = "Ooops, the reservation has already been booked."
        render :'show.html.erb' and return
      end
    end
  end

  def trending
    @hotels = Hotel.most_popular
  end

  private

    def hotel_params
      params.require(:hotel).permit(
        # params for API:
        :city, :checkin_date, :checkout_date,:guests, :hotelId,
        # params from city_hotels and user_hotels nested routes:
        :city_id, :user_id
      )
    end

    def check_city_id
      if params[:city_id]
        @nested_city = current_user.cities.find_by(id: params[:city_id])
        @hotels = current_user.hotels_by_city(params[:city_id])
        if @nested_city.nil? 
          flash[:msg] = "City not found."
          redirect_to cities_path and return    
        elsif params[:id] && current_user.hotels.find_by(id: params[:id], city_id: params[:city_id]).nil?
          flash[:msg] = "Hotel not found for this city." 
          redirect_to city_hotels_path(@nested_city) and return
        end
      end
    end

    def check_user_id
      if params[:user_id] 
        @nested_user = User.find_by(id: params[:user_id])
        if @user != @nested_user
          flash[:msg] = "Users can only see their own hotels."
          redirect_to user_hotels_path(@user) and return
        end
        # @hotels = @nested_user.all_hotels_sorted
        # todo: make retrieve+hotels_method build the hotels_list if list is empty
        hotel_ids = HotelTracker::ForUser.retrieve_hotels_list(@nested_user)
        hotel_ids = HotelTracker::ForUser.new(@nested_user).hotel_ids if hotel_ids.empty?
        @hotels = Hotel.find(hotel_ids)
        render :index and return
      end
    end

    def filter_city_name
      if params[:city].length == 3
        iatacode = params[:city]
      else
        # grab the content inside the parenthesis
        iatacode = params[:city][/\((.*?)\)/, 1]
        if !iatacode.nil? && iatacode.length < 3
          flash[:msg] = "Please select a city from the list or use the 3 letters IATA code for your desired city."
          render :'index.html.erb' and return
        end
      end
      iatacode
    end

    def convert_dates
      dates = params[:dates].split("-")
      start = dates[0].strip.split("/")
      last = dates[1].strip.split("/")
      checkin_date = "#{start[2]}-#{start[0]}-#{start[1]}"
      checkout_date = "#{last[2]}-#{last[0]}-#{last[1]}"
      [checkin_date, checkout_date]
      # Date.strptime(checkin_date, '%Y-%m-%d')
      # Date.strptime(checkout_date, '%Y-%m-%d')
    end

end

app/helpers/hotels_helper.rb
module HotelsHelper
  
end

app/views/hotels/_hotel_search.html.erb
<%= form_with url: "/hotel_search", html: {class: "row g-4 hotel-search"}, method: :get do |f| %>
  <div class="col-sm-4">
    <%= f.label :city, "Search for:", :class => "form-label"%>
    <%= f.text_field :city, :class => "form-control searchName", :placeholder => "City name", list: "city_name" %>
    <datalist id="city_name">
    </datalist>
  </div>

  <div class="col-sm-4">
    <%= f.label :testing, "Select your dates:", :class => "form-label" %>
    <%= f.text_field :dates, :class => "form-control", id:"dates", data: {behavior: "daterangepicker" } %>
  </div>

  <div class="col-sm-2">
    <%= f.label :guests, "Guests:", :class => "form-label" %>
    <%= f.select(:guests, [1,2,3,4,5], {}, {class: "form-select"}) %>
  </div>

  <div id="search-button" class="col-sm">
      <%= f.submit "Search", class: "btn btn-secondary" %>
  </div>
<% end %>

<%= javascript_pack_tag 'city', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'calendar', 'data-turbolinks-track': 'reload' %>

app/views/hotels/_info.html.erb
<h2><%= hotel.name %></h2>
<p><%= hotel.description  %></p>
<p>Address:<br>
<%= hotel.address %>
</p>
<p>Amenities:<br>
<%= hotel.amenities %>
</p>

app/views/hotels/_search_results.html.erb
<div class="row">
  <h3><%= link_to hotel.name, search_results_path(hotelId: hotel.hotelId) %></h3>
  <% reservation_data = @user.unbooked_reservation(hotel) %> 
  <p>
    Guests: <%= reservation_data.guests %><br>
    Beds: <%= reservation_data.room.beds %><br>
    Price: <%= reservation_data.currency %> <%= reservation_data.price %>
  </p>
</div>

app/views/hotels/index.html.erb
<div class= "view index" >
  <div>
    <%= render 'hotel_search' unless @nested_city || @nested_user %>
  </div>
  
  <%= render partial: 'messages/msg' %>
 
  <div class="series" id="hotels" >
    <%# If the @hotels variable is not defined, only show the hotel search form from above %>
    <% if @hotels %>
      <%# @nested_city is defined when accessing the hotels index page via a city nested rooute %>
      <%# @nested_user is defined when accessing the hotels index via a user nested route %>
      <%# show the hotel search results if user is accessing the hotels index page via regular (non-nested) route %>
      <% if @nested_city.nil? && @nested_user.nil? %>
        <div class="container">
          <%= render partial: 'search_results', collection: @hotels, as: :hotel %>
        </div>
      <% else %>
        <h1><%= @nested_city ? "My Hotels in #{@nested_city.name.titleize}" : "My Hotels" %></h1>
        <br>
        <% if @hotels.empty? %>
          <p>You haven't booked any hotels yet!!!</p>
        <% else %>
          <ul>
            <% @hotels.each do |hotel| %>
              <div>
                <li>
                  <h5><%= link_to hotel.name, @nested_city ? "#{city_hotel_path(@nested_city, hotel.id)}" : "#{hotel_path(hotel.id)}" %></h5>
                </li>
                <br>
              </div>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/hotels/show.html.erb
<div class="view" id="hotel-show">
  
  <%= render partial: 'messages/msg' %>
  
  <%# This view is composed of three components: hotel, reservation, and reviews %>

  <%# Hotel component %>
  <div class="box" id="hotel">
    <%= render partial: 'hotels/info', locals: { hotel: @hotel}  %>
  </div>

  <%# Reservation component %>
  <div class="box" id="reservations">
    <%# An unbooked_reservation occurs when the user searches for hotels and clicks on a hotel link from search results %>
    <%# the reservation displayed in the hotel show page is an unbooked reservation %>
    <% unbooked_reservation = @user.unbooked_reservation(@hotel) %>
    <% if unbooked_reservation %>  
      <h3>Offer:</h3>
      <%= render partial: 'reservations/info_no_links', locals: { reservation: unbooked_reservation } %><br>
      <a href="/reserve/<%= @hotel.hotelId %>/<%= unbooked_reservation.code %>">Reserve</a>
    <%# single_reservation occurs when user clicks on a reservation's hotel name link in reservations index page %>
    <%# which activates the hotel show page with the clicked reservation %>
    <% elsif @single_reservation %>
      <h3>Reservation</h3>
      <p><%= upcoming_single_reservation?(@single_reservation) ? 'Upcoming' : 'Previous' %></p>
      <%= render partial: 'reservations/info', locals: {reservation: @single_reservation} %>
    <% else %>
      <%# upcoming_reservations and previous_reservations occur when user clicks on a hotel name in the hotels index page %>
      <h3>Reservations</h3>
      <% upcoming_reservations = @user.upcoming_reservations(@hotel) %>
      <% if !upcoming_reservations.empty? %>
        <p>Upcoming:</p>
        <%= render partial: 'reservations/info', collection: upcoming_reservations, as: :reservation %>
      <% end %>
      <% previous_reservations = @user.previous_reservations(@hotel) %>
      <% if !previous_reservations.empty? %>
        <p>Previous:</p>
        <%= render partial: 'reservations/info', collection: previous_reservations, as: :reservation %>
      <% end %>
    <% end %>
  </div>

  <%# Reviews component %>
  <div class="box" id="reviews">
    <h3>Reviews</h3>
    <div>
      <% @hotel.reviews.includes(reservation: [:user]).each do |review| %>
        <p>
          <%= review.reservation.user.username %><br>
          Posted on <%= review.creation_time %>:<br>
        </p>
        <blockquote class="review-block">
          "<em><%= review.description %></em>"
        </blockquote>
      <% end %>  
    </div>
  </div>

</div>

app/views/hotels/trending.html.erb
 <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">

  
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <% @hotels.each_with_index do |hotel, index| %>
        <% if index == 0 %>
          <div class="carousel-item active">
        <% else %>
          <div class="carousel-item">
        <% end %>
            <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
            <div class="container">
              <div class="carousel-caption text-start">
                <h1><%= hotel.name %></h1> 
                <p><%= hotel.city.name %></p>
                <% if index == 0 %>
                 <p><a class='btn btn-lg btn-primary' data-id="button-1">Reserve today</a></p>
                <% elsif index == 1 %>
                 <p><a class="btn btn-lg btn-primary" data-id="button-2">Learn more</a></p> 
                <% elsif index == 2 %>
                 <p><a class="btn btn-lg btn-primary" data-id="button-3">Browse gallery</a></p> 
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <% @hotels.each.with_index(1) do |hotel, index| %>
      <div class="row featurette" id="hotel-<%= index %>" >
        <div class="col-md-7">
          <h2 class="featurette-heading"><%= hotel.name %></h2>
          <span class="text-muted"><%= hotel.city.name %></span>
          <p class="lead"><%= hotel.description %></p>
        </div>
        <div class="col-md-5">
          <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
        </div>
      </div>
      <hr class="featurette-divider">
    <% end %>

  <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

  <script>

    function activate() {
      const hotelButtons = document.getElementsByClassName('btn');
      for (const btn of hotelButtons) {
        btn.addEventListener('click', function(e) { 
          e.preventDefault();
          let string = e.target.dataset.id
          let number = string[string.length-1]
          document.getElementById(`hotel-${number}`).scrollIntoView({behavior: 'smooth'});
        })
      }
    }

    activate()

  </script>


  





      
  