config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :cities, :only => [:index]
  resources :hotels, :only => [:index, :show]
  resources :reservations, :only => [:index, :show]
  resources :reviews, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :users, :only =>[:create, :show]
  
  # Sessions controller routes
  root 'sessions#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/signup', to: 'users#new', as: 'signup'

  # Omniuath routes
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  #  Amadeus API routes
  get "hotel_search", to: "hotels#index"
  get "search_results", to: "hotels#search_results"
  get "/reserve/:hotelId/:code", to: "hotels#reserve"

  # Nested routes
  resources :cities, only: [:show] do
    resources :hotels, only: [:index, :show]
  end

  resources :users, only: [:show] do
    resources :hotels, only: [:index]
  end

  resources :reservations, only: [:show] do
    resources :reviews, only: [:show, :new]
  end

  get 'trending', to: 'hotels#trending'
  get 'datalist', to: 'cities#datalist'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :check_reservation_id, :check_review_id, only: [:new, :show, :edit]
  before_action :check_reservation_id, only: [:new, :show]
  before_action :check_review_id, only: [:show, :edit, :update]

  def index
    @reviews = current_user.all_reviews_sorted
  end

  def new
    if @reservation && @reservation.checkout_date >= Date.today.to_s
      flash[:msg] = "Reservations open for review one day after the reservation's checkout date"
      redirect_to reservations_path
    else
      #  If the new review is requested from the nested new_reservation_review path, catch the nested reservation's id
      @review = Review.new(reservation_id: params[:reservation_id])
    end
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      flash[:msg] = "Review succesfully created"
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    if @review.update(review_params)
      flash[:msg] = "Review succesfully updated"
      redirect_to review_path(@review)
    else
      render :edit
    end
  end

  def destroy
    review = Review.find_by(id: params[:id])
    review.destroy
    flash[:msg] = "Review successfully deleted"
    redirect_to reviews_path
  end

  private
  def review_params
    params.require(:review).permit(:description, :reservation_id)
  end

  def check_reservation_id
    @reservation = nil
    if params[:reservation_id] 
      @reservation = current_user.reservations.find_by(id: params[:reservation_id])
      if !@reservation
        flash[:msg] = "Reservation not found"
        redirect_to reservations_path and return
      end
    end
    @reservation
  end

  def check_review_id
    @review = current_user.reviews.find_by(id: params[:id])
    if !@review
      flash[:msg] = "Review not found"
      redirect_to reviews_path and return
    end
    @review
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def reservation_id_field(review, user)
    # if the new review does not have a reservation, provide a select field to choose a reservation for the review
    if review.reservation.nil?
      select_tag "review[reservation_id]", options_from_collection_for_select(user.open_for_review_reservations, :id, :hotel_and_checkin, :include_blank => true)
    else
      hidden_field_tag "review[reservation_id]", review.reservation_id
    end
  end
  
end

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
  <%# reservation_id_field is defined in reviews_helper %>
  <%= reservation_id_field(@review, @user) %><br>
  <%= f.label 'Review description:' %><br>
  <%= f.text_area :description %><br>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>
<%= render partial: 'messages/error', locals: { agnostic: @review } %>
<p><%= @review.reservation.hotel.name %></p>
<p><%= @review.reservation.hotel.city.name %></p>
<%= render partial: 'reservations/info_no_links', locals: {reservation: @review.reservation} %><br>
<%= render 'form' %>

<%= link_to "Cancel", :back %>

app/views/reviews/index.html.erb
<%= render partial: 'messages/msg' %>

<h1>My Reviews</h1><br>
<% any_reviews = @reviews.exists? %>
<% if @user.open_for_review_reservations.exists? %>
  <p>You have open-for-review reservations: <%= link_to "New Review", new_review_path %></p><br>
<% elsif !any_reviews %>
  <p>You don't currently have open-for-review reservations. Reviews open one day after a reservation's checkout date.</p><br>
<% end %>

<% if any_reviews %>
  <ul>
    <% @reviews.each do |review| %>  
      <li class="review-block">
        <h3><%= review.reservation.hotel.name %></h3>
        <p><%= review.reservation.hotel.city.name %></p>
        <h6>Review description:</h6>
        <em>"<%= review.description -%>"</em><br>
        <%= link_to 'Show review', review_path(review) %><br><br>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= render partial: 'messages/error', locals: { agnostic: @review } %>
<%# the new review comes with its parent reservation loaded when opened through the new_reservation_review path %>
<%# in a hotel show page or reservations index page; otherwise the new review comes with no reservation when opened  %>
<%# through the New Review link in the reviews index page with the option of selecting a reservation from a dropdown field in the below form %>
<% unless @review.reservation.nil? %>
  <p><%= @review.reservation.hotel.name %><br>
     <%= @review.reservation.hotel.city.code %>
  </p>
  <%= render partial: 'reservations/info_no_links', locals: {reservation: @review.reservation} %><br>
<% end %>
<%= render 'form' %>
<%= link_to "Cancel", :back %>

app/views/reviews/show.html.erb
<%= render partial: 'messages/msg' %>

<h2>Review for:</h2> 
<p>
  <%= @review.reservation.hotel.name %><br>
  <%= @review.reservation.hotel.city.name %><br>
  <%= render partial: 'reservations/info_no_links', locals: {reservation: @review.reservation} %>
</p>

<h3>Review description:</h3>
<em>"<%= @review.description %>"</em><br><br>

<%= link_to 'Edit review', edit_review_path(@review) %><br>
<%= link_to 'Delete review', @review, method: :delete, data: { confirm: "Are you sure?" } %><br>
<%= link_to 'Go to reviews', reviews_path %>