config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :cities, :only => [:index]
  resources :hotels, :only => [:index, :show]
  resources :reservations, :only => [:index, :show]
  resources :reviews, :only => [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :users, :only =>[:create, :show]
  
  # Sessions controller routes
  root 'sessions#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/signup', to: 'users#new', as: 'signup'

  # Omniuath routes
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  #  Amadeus API routes
  get "hotel_search", to: "hotels#index"
  get "search_results", to: "hotels#search_results"
  get "/reserve/:hotelId/:code", to: "hotels#reserve"

  # Nested routes
  resources :cities, only: [:show] do
    resources :hotels, only: [:index, :show]
  end

  resources :users, only: [:show] do
    resources :hotels, only: [:index]
  end

  resources :reservations, only: [:show] do
    resources :reviews, only: [:show, :new]
  end

  get 'trending', to: 'hotels#trending'
  get 'datalist', to: 'cities#datalist'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel Booking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    
  </head>

  <body>
    <header>
      <% if session[:user_id] %>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="/hotel_search">Hotel Booking</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link <%= 'active' if current_page?(hotel_search_path) || current_page?(search_results_path) || request.path.include?('reserve') %>" aria-current="page" href="/hotel_search">Hotel Search</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link <%= 'active' if current_page?(user_hotels_path(@user.id)) or (!request.path.include?('cities') && request.path.include?('hotels')) %>" aria-current="page" href="/users/<%= @user.id %>/hotels">Hotels</a>
                </li>
                <li class="nav-item">
                  <% upcoming = Rails.cache.redis.with {|c| c.get(HotelTracker.upcoming_re_counter_cache_key(@user)) } %> 
                  <a class="nav-link <%= 'active' if request.path.include? 'reservations' %>" aria-current="page" href="/reservations">Reservations (<%= upcoming %>)</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link <%= 'active' if request.path.include? 'cities' %>" aria-current="page" href="/cities">Cities</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link <%= 'active' if !request.path.include?('reservations') && request.path.include?('reviews') %>" aria-current="page" href="/reviews">Reviews</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link <%= 'active' if current_page?(trending_path) %>" aria-current="page" href="/trending">Trending</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="/logout">Logout</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      <% end %>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      <div>
    <main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    
    
  </body>
  
  
</html>